export const API_URL = import.meta.env.VITE_API_URL
export const API_KEY = import.meta.env.VITE_API_KEY
console.log('API_URL:', import.meta.env.VITE_API_URL)
console.log('API_KEY:', import.meta.env.VITE_API_KEY)

export const MOCK_DATA = { // Mock data generated by Claude
  "prices": [
    0.06, 0.05, 0.05, 0.05, 0.06, 0.08,
    0.15, 0.28, 0.30, 0.25, 0.20, 0.18,
    0.16, 0.15, 0.16, 0.18, 0.22, 0.29,
    0.31, 0.30, 0.25, 0.18, 0.12, 0.08
  ],
  "load": [0.4, 0.3, 0.3, 0.3, 0.4, 0.6,
    1.2, 1.8, 1.5, 1.2, 1.0, 0.9,
    0.8, 0.8, 0.9, 1.0, 1.2, 1.8,
    2.1, 2.0, 1.6, 1.2, 0.8, 0.5
  ],
  "battery": {
    "capacity_kwh": 10.0,
    "max_charge_kw": 5.0,
    "max_discharge_kw": 5.0,
    "efficiency": 0.95,
    "initial_soc_kwh": 5.0
  }
};